services:
  - type: web
    name: cop-api
    env: python
    buildCommand: "./deploy/scripts/build.sh"
    startCommand: "gunicorn config.gateways.wsgi:application --workers=8"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
