# Generated by Django 4.1.5 on 2023-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("mentor", "mentor"),
                    ("mentee", "mentee"),
                    ("consortium_member", "consortium_member"),
                ],
                default="mentee",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
