# Generated by Django 4.1.5 on 2023-02-02 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=65, verbose_name="forum name")),
                ("creator", models.CharField(max_length=20, verbose_name="Creator")),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="forums", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
