# Generated by Django 4.1.5 on 2023-02-03 19:24

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forum",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveField(
            model_name="forum",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="forum",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="forum",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forum",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
