# Generated by Django 4.1.5 on 2023-02-08 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="members",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
