# Generated by Django 4.1.5 on 2023-02-06 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forums", "0002_alter_forum_options_remove_forum_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="creator",
            field=models.CharField(max_length=20, verbose_name="creator"),
        ),
        migrations.AlterField(
            model_name="forum",
            name="members",
            field=models.ManyToManyField(
                related_name="forums",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
        migrations.AlterField(
            model_name="forum",
            name="name",
            field=models.CharField(max_length=65, verbose_name="name"),
        ),
    ]
