# Generated by Django 4.1.5 on 2023-02-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_role_user_address_user_current_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="images/avatars/default.png",
                upload_to="images/avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
