# Generated by Django 4.1.5 on 2023-02-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FORUM_MODEL),
        ("users", "0004_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
        migrations.AddField(
            model_name="user",
            name="forums",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.FORUM_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("mentor", "mentor"),
                    ("mentee", "mentee"),
                    ("consortium_member", "consortium_member"),
                ],
                db_index=True,
                default="mentee",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
