# Generated by Django 4.1.5 on 2023-02-17 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FORUM_MODEL),
        ("users", "0005_remove_user_user_type_user_forums_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="forums",
        ),
        migrations.AddField(
            model_name="user",
            name="forum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.FORUM_MODEL,
            ),
        ),
    ]
