# Generated by Django 4.1.5 on 2023-02-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_forum_user_forums"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="dob",
            new_name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="forums",
        ),
    ]
