# Generated by Django 4.1.5 on 2023-02-08 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forums", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="members",
            field=models.ManyToManyField(
                related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
