# Generated by Django 4.1.5 on 2023-02-09 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forums", "0003_alter_forum_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="members",
            field=models.ManyToManyField(
                db_index=True, related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
