# Generated by Django 4.1.5 on 2023-02-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0004_alter_forum_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forum",
            options={"verbose_name": "forum", "verbose_name_plural": "forums"},
        ),
    ]
