# Generated by Django 4.1.5 on 2023-02-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comment_rename_text_post_content_likedcomment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="commented_by",
        ),
        migrations.RenameField(
            model_name="likedcomment",
            old_name="user",
            new_name="liked_by",
        ),
        migrations.RenameField(
            model_name="likedpost",
            old_name="user",
            new_name="liked_by",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="posted_by",
        ),
    ]
